"""Data backbone: populate the cache for the basket and document coverage.

Downloads the 5m base interval for BTCUSDT/ETHUSDT/SOLUSDT from each
symbol's listing through the holdout boundary (2025-01-01, exclusive) —
the holdout lock forbids fetching beyond it until #18 sign-off. Higher
timeframes derive by resampling; spot checks confirm the resample matches
exchange-native candles.

Usage:
    python -m tamad.backbone            # sync basket, write docs/DATA_COVERAGE.md
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from tamad import data

BASKET = ["BTCUSDT", "ETHUSDT", "SOLUSDT"]
BASE_INTERVAL = "5m"
EARLIEST = "2017-01-01"
HOLDOUT_START = pd.Timestamp("2025-01-01", tz="UTC")
COVERAGE_DOC = Path(__file__).resolve().parent.parent / "docs" / "DATA_COVERAGE.md"


def sync(symbol: str, start: str = EARLIEST, end: str | pd.Timestamp = HOLDOUT_START) -> pd.DataFrame:
    """Fill the cache for one symbol and return its base candles."""
    if data.to_utc(end) > HOLDOUT_START:
        raise SystemExit(
            f"HOLDOUT LOCK: backbone may not fetch data beyond {HOLDOUT_START.date()}."
        )
    return data.get_candles(symbol, BASE_INTERVAL, start, end)


def spot_check(symbol: str, interval: str, start: str, end: str) -> bool:
    """Does resampling the base interval reproduce exchange-native candles?"""
    base = data.get_candles(symbol, BASE_INTERVAL, start, end)
    native = data.get_candles(symbol, interval, start, end)
    resampled = data.resample_ohlcv(base, interval)
    resampled = resampled.loc[(resampled.index >= native.index[0]) & (resampled.index <= native.index[-1])]
    if len(native) != len(resampled):
        return False
    return bool(
        (native[data.OHLCV].round(8) == resampled[data.OHLCV].round(8)).all().all()
    )


def coverage_report(symbols: list[str] = BASKET) -> str:
    lines = [
        "# Data coverage",
        "",
        f"Base interval: {BASE_INTERVAL}, cached monthly under `data/cache/` (gitignored).",
        f"Coverage ends at the **holdout boundary {HOLDOUT_START.date()}** — later months stay",
        "undownloaded until the holdout sign-off on issue #18. Generated by `python -m tamad.backbone`.",
        "",
        "| Symbol | First bar | Last bar | Bars | Gaps | Largest gap (bars) |",
        "|---|---|---|---|---|---|",
    ]
    for symbol in symbols:
        df = data.get_candles(symbol, BASE_INTERVAL, EARLIEST, HOLDOUT_START)
        gaps = data.find_gaps(df, BASE_INTERVAL)
        largest = int(gaps["missing_bars"].max()) if len(gaps) else 0
        lines.append(
            f"| {symbol} | {df.index[0]} | {df.index[-1]} | {len(df):,} | {len(gaps)} | {largest} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    for symbol in BASKET:
        df = sync(symbol)
        print(f"{symbol}: {len(df):,} bars {df.index[0]} .. {df.index[-1]}")
    checks = []
    for symbol in BASKET:
        for interval in ("15m", "1h"):
            ok = spot_check(symbol, interval, "2023-03-01", "2023-04-01")
            checks.append(f"{symbol} {interval}: {'OK' if ok else 'MISMATCH'}")
            print(f"spot check {checks[-1]}")
    report = coverage_report()
    report += "\nResample spot checks (2023-03): " + ", ".join(checks) + "\n"
    COVERAGE_DOC.write_text(report, encoding="utf-8")
    print(f"coverage written to {COVERAGE_DOC}")


if __name__ == "__main__":
    main()
